name = "ModelChecking"
uuid = "61e30682-4206-4892-adea-f6915658cc6b"
authors = ["Kwesi Rutledge <thesolitaryecrivain@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
